services:
  nginx:
    image: nginx:alpine
    container_name: kachabazar_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - store
      - admin
      - backend
    restart: unless-stopped
    networks:
      - bf

  store:
    build:
      context: ./store
      dockerfile: Dockerfile
    container_name: kachabazar_store
    env_file: ./store/.env.docker
    restart: unless-stopped
    networks:
      - bf

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: kachabazar_admin
    restart: unless-stopped
    networks:
      - bf

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kachabazar_backend
    env_file: ./backend/.env
    volumes:
      - uploads_data:/app/public/uploads
    restart: unless-stopped
    networks:
      - bf

volumes:
  uploads_data:

networks:
  bf:
    external: true
