const bcrypt = require("bcryptjs");

const deliveryBoys = [
  {
    name: {
      en: "James Rodriguez",
    },
    image: "https://i.ibb.co/d294W8Y/team-4.jpg",
    email: "james.rider@gmail.com",
    password: bcrypt.hashSync("12345678"),
    phone: "708-628-3122",
    address: "123 Main St",
    city: "New York",
    country: "USA",
    zipCode: "10001",
    vehicleType: "bike",
    vehicleNumber: "NY-1234",
    licenseNumber: "DL-98765",
    status: "active",
    availability: "available",
    totalDeliveries: 0,
    completedDeliveries: 0,
    cancelledDeliveries: 0,
    totalEarnings: 0,
    averageRating: 0,
    totalRatings: 0,
    joiningDate: new Date("2025-06-15"),
  },
  {
    name: {
      en: "Michael Chen",
    },
    image: "https://i.ibb.co/m5B0hK4/team-8.jpg",
    email: "michael.rider@gmail.com",
    password: bcrypt.hashSync("12345678"),
    phone: "708-488-9728",
    address: "456 Oak Ave",
    city: "Los Angeles",
    country: "USA",
    zipCode: "90001",
    vehicleType: "scooter",
    vehicleNumber: "LA-5678",
    licenseNumber: "DL-54321",
    status: "active",
    availability: "available",
    totalDeliveries: 0,
    completedDeliveries: 0,
    cancelledDeliveries: 0,
    totalEarnings: 0,
    averageRating: 0,
    totalRatings: 0,
    joiningDate: new Date("2025-03-20"),
  },
  {
    name: {
      en: "David Williams",
    },
    image: "https://i.ibb.co/SNN7JCX/team-6.jpg",
    email: "david.rider@gmail.com",
    password: bcrypt.hashSync("12345678"),
    phone: "914-623-6873",
    address: "789 Pine Rd",
    city: "Chicago",
    country: "USA",
    zipCode: "60601",
    vehicleType: "car",
    vehicleNumber: "CH-9012",
    licenseNumber: "DL-11111",
    status: "active",
    availability: "available",
    totalDeliveries: 0,
    completedDeliveries: 0,
    cancelledDeliveries: 0,
    totalEarnings: 0,
    averageRating: 0,
    totalRatings: 0,
    joiningDate: new Date("2025-01-10"),
  },
  {
    name: {
      en: "Robert Johnson",
    },
    image: "https://i.ibb.co/GWVWYNn/team-7.jpg",
    email: "robert.rider@gmail.com",
    password: bcrypt.hashSync("12345678"),
    phone: "949-202-2913",
    address: "321 Elm St",
    city: "Houston",
    country: "USA",
    zipCode: "77001",
    vehicleType: "bicycle",
    vehicleNumber: "N/A",
    licenseNumber: "DL-22222",
    status: "inactive",
    availability: "offline",
    totalDeliveries: 0,
    completedDeliveries: 0,
    cancelledDeliveries: 0,
    totalEarnings: 0,
    averageRating: 0,
    totalRatings: 0,
    joiningDate: new Date("2025-08-01"),
  },
  {
    name: {
      en: "Alex Thompson",
    },
    image: "https://i.ibb.co/XjwBLcK/team-2.jpg",
    email: "alex.rider@gmail.com",
    password: bcrypt.hashSync("12345678"),
    phone: "616-738-0407",
    address: "555 Cedar Ln",
    city: "Phoenix",
    country: "USA",
    zipCode: "85001",
    vehicleType: "van",
    vehicleNumber: "PH-3456",
    licenseNumber: "DL-33333",
    status: "active",
    availability: "available",
    totalDeliveries: 0,
    completedDeliveries: 0,
    cancelledDeliveries: 0,
    totalEarnings: 0,
    averageRating: 0,
    totalRatings: 0,
    joiningDate: new Date("2025-04-05"),
  },
];

module.exports = deliveryBoys;
