services:
  kachabazar_store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kachabazar_store
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api
      NEXT_SERVER_API_BASE_URL: http://kachabazar_backend:5056/v1
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external:
      name: bf
