import React, { useContext, useMemo, useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { useTranslation } from "react-i18next";
import { FiPlus, FiTrash2, FiZoomIn, FiDownload, FiEdit } from "react-icons/fi";
import { Eye, Copy, Pencil, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import {
  keepPreviousData,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";
import CategoryServices from "@/services/CategoryServices";

//internal import
import { useAction } from "@/context/ActionContext";
import useToggleDrawer from "@/hooks/useToggleDrawer";
import useUtilsFunction from "@/hooks/useUtilsFunction";
import UploadMany from "@/components/common/UploadMany";
import ProductServices from "@/services/ProductServices";
import { SidebarContext } from "@/context/SidebarContext";
import MainDrawer from "@/components/drawer/MainDrawer";
import ProductDrawer from "@/components/drawer/ProductDrawer";
import useProductFilter from "@/hooks/useProductFilter";
import DeleteModal from "@/components/modal/DeleteModal";
import BulkActionDrawer from "@/components/drawer/BulkActionDrawer";
import AnimatedContent from "@/components/common/AnimatedContent";
import { SectionTitle } from "@/components/common/SectionTitle";
import { ButtonGroup } from "@/components/common/ButtonGroup";
import { DynamicTable } from "@/components/table/DynamicTable";
import { DynamicTableColumnHeader } from "@/components/table/DynamicTableColumnHeader";
import { DynamicTableRowActions } from "@/components/table/DynamicTableRowActions";
import { selectColumn } from "@/components/table/selectColumn";
import ShowHideButton from "@/components/table/ShowHideButton";
import { notifySuccess, notifyError } from "@/utils/toast";

const Products = () => {
  const queryClient = useQueryClient();

  const {
    title,
    handleDeleteMany,
    handleUpdateMany,
    handleUpdate,
    handleModalOpen,
  } = useToggleDrawer();
  const {
    open,
    setOpen,
    selectedId,
    selectedIds,
    setSelectedIds,
    isCheckAll,
    handleSelectAll,
    toggleDrawer,
  } = useAction();

  // Local table state (per-page to avoid cross-page interference)
  const [sorting, setSorting] = useState([]);
  const [rowSelection, setRowSelection] = useState({});
  const [columnFilters, setColumnFilters] = useState([]);
  const [columnVisibility, setColumnVisibility] = useState({});

  const { t } = useTranslation();
  const { currency, formatPrice, showingTranslateValue } = useUtilsFunction();

  // Server-side filter state
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [searchText, setSearchText] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("");
  const [sortedField, setSortedField] = useState("");

  const {
    data,
    isLoading: loading,
    error,
  } = useQuery({
    queryKey: [
      "products",
      currentPage,
      pageSize,
      categoryFilter,
      searchText,
      sortedField,
    ],
    queryFn: () =>
      ProductServices.getAllProducts({
        page: currentPage,
        limit: pageSize,
        category: categoryFilter || "",
        title: searchText || "",
        price: sortedField || "",
      }),
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
    placeholderData: keepPreviousData,
  });

  const {
    filename,
    isDisabled,
    serviceData,
    handleSelectFile,
    handleUploadMultiple,
    handleRemoveSelectFile,
  } = useProductFilter(data?.products);

  // Fetch ALL categories for the filter dropdown
  const { data: allCategories } = useQuery({
    queryKey: ["categories-all"],
    queryFn: CategoryServices.getAllCategories,
    staleTime: 10 * 60 * 1000,
  });

  const handleResetFilters = useCallback(() => {
    setSearchText("");
    setCategoryFilter("");
    setSortedField("");
    setCurrentPage(1);
  }, []);

  // Handle duplicate product
  const handleDuplicateProduct = useCallback(
    async (product) => {
      try {
        // Create a copy of the product without _id and with "(Copy)" in title
        const duplicatedProduct = {
          productId: "", // Will be generated by backend
          sku: product.sku ? `${product.sku}-copy` : "",
          barcode: product.barcode ? `${product.barcode}-copy` : "",
          title: Object.keys(product.title || {}).reduce((acc, lang) => {
            acc[lang] = product.title[lang]
              ? `${product.title[lang]} (Copy)`
              : "";
            return acc;
          }, {}),
          description: product.description || {},
          slug: product.slug ? `${product.slug}-copy-${Date.now()}` : "",
          categories: product.categories || [],
          category: product.category || "",
          image: product.image || [],
          stock: product.stock || 0,
          tag: product.tag || "[]",
          prices: {
            price: product.prices?.price || 0,
            originalPrice: product.prices?.originalPrice || 0,
            discount: product.prices?.discount || 0,
          },
          isCombination: product.isCombination || false,
          variants: product.variants || [],
          status: product.status || "show",
          seo: product.seo || {},
        };

        const res = await ProductServices.addProduct(duplicatedProduct);
        if (res) {
          queryClient.invalidateQueries({ queryKey: ["products"] });
          notifySuccess("Product duplicated successfully!");
        }
      } catch (err) {
        notifyError(
          err?.response?.data?.message || "Failed to duplicate product",
        );
      }
    },
    [queryClient],
  );

  // ─── Table Columns ──────────────────────────────────────────────────
  // Category options for the filter dropdown
  const categoryOptions = useMemo(() => {
    const cats = Array.isArray(allCategories)
      ? allCategories
      : allCategories?.categories || [];
    return cats.reduce((acc, cat) => {
      const name = showingTranslateValue(cat?.name);
      if (name && !acc.find((o) => o.label === name)) {
        acc.push({ label: name, value: cat._id });
      }
      return acc;
    }, []);
  }, [allCategories, showingTranslateValue]);

  const columns = useMemo(
    () => [
      selectColumn,
      {
        accessorKey: "title",
        header: ({ column }) => (
          <DynamicTableColumnHeader
            column={column}
            title={t("ProductNameTbl")}
          />
        ),
        cell: ({ row }) => {
          const product = row.original;
          return (
            <div className="flex items-center gap-3">
              <Avatar className="hidden md:block bg-muted p-1 shadow-none h-8 w-8">
                <AvatarImage
                  src={
                    product?.image?.[0] ||
                    "https://res.cloudinary.com/ahossain/image/upload/v1655097002/placeholder_kvepfp.png"
                  }
                  alt="product"
                />
                <AvatarFallback>P</AvatarFallback>
              </Avatar>
              <span className="text-sm font-medium">
                {showingTranslateValue(product?.title)?.substring(0, 28)}
              </span>
            </div>
          );
        },
        enableSorting: true,
      },
      {
        accessorKey: "category",
        header: ({ column }) => (
          <DynamicTableColumnHeader column={column} title={t("CategoryTbl")} />
        ),
        cell: ({ row }) => (
          <span className="text-sm">
            {showingTranslateValue(row.original?.category?.name)}
          </span>
        ),
        enableSorting: true,
      },
      {
        accessorKey: "originalPrice",
        header: ({ column }) => (
          <DynamicTableColumnHeader column={column} title={t("PriceTbl")} />
        ),
        cell: ({ row }) => {
          const product = row.original;
          return (
            <span className="text-sm font-semibold">
              {formatPrice(
                product?.isCombination
                  ? product?.variants?.[0]?.originalPrice
                  : product?.prices?.originalPrice,
              )}
            </span>
          );
        },
        enableSorting: true,
      },
      {
        accessorKey: "salePrice",
        header: ({ column }) => (
          <DynamicTableColumnHeader column={column} title={t("SalePrice")} />
        ),
        cell: ({ row }) => {
          const product = row.original;
          return (
            <span className="text-sm font-semibold">
              {formatPrice(
                product?.isCombination
                  ? product?.variants?.[0]?.price
                  : product?.prices?.price,
              )}
            </span>
          );
        },
        enableSorting: true,
      },
      {
        accessorKey: "stock",
        header: ({ column }) => (
          <DynamicTableColumnHeader column={column} title={t("StockTbl")} />
        ),
        cell: ({ row }) => (
          <span className="text-sm">{row.original.stock}</span>
        ),
        enableSorting: true,
      },
      {
        accessorKey: "stockStatus",
        header: ({ column }) => (
          <DynamicTableColumnHeader column={column} title={t("StatusTbl")} />
        ),
        cell: ({ row }) =>
          row.original.stock > 0 ? (
            <Badge variant="success">{t("Selling")}</Badge>
          ) : (
            <Badge variant="danger">{t("SoldOut")}</Badge>
          ),
        enableSorting: false,
      },
      {
        id: "details",
        header: () => (
          <span className="text-center block">{t("DetailsTbl")}</span>
        ),
        cell: ({ row }) => (
          <Link
            to={`/product/${row.original._id}`}
            className="flex justify-center text-muted-foreground hover:text-primary"
          >
            <FiZoomIn className="w-5 h-5" />
          </Link>
        ),
        enableSorting: false,
        enableHiding: false,
      },
      {
        id: "published",
        accessorFn: (row) => row.status,
        header: ({ column }) => (
          <DynamicTableColumnHeader column={column} title={t("PublishedTbl")} />
        ),
        cell: ({ row }) => (
          <ShowHideButton id={row.original._id} status={row.original.status} />
        ),
        enableSorting: false,
        enableHiding: false,
      },
      {
        id: "featured",
        accessorFn: (row) => (row.isFeatured ? "show" : "hide"),
        header: ({ column }) => (
          <DynamicTableColumnHeader column={column} title={t("Featured")} />
        ),
        cell: ({ row }) => (
          <ShowHideButton
            id={row.original._id}
            status={row.original.isFeatured ? "show" : "hide"}
          />
        ),
        enableSorting: false,
        enableHiding: false,
      },
      {
        id: "actions",
        header: () => (
          <span className="text-right block">{t("ActionsTbl")}</span>
        ),
        cell: ({ row }) => (
          <DynamicTableRowActions
            row={row}
            actions={[
              {
                key: "view",
                label: t("View"),
                icon: Eye,
                onClick: () => {},
                href: `/product/${row.original._id}`,
              },
              {
                key: "duplicate",
                label: t("Duplicate"),
                icon: Copy,
                onClick: () => handleDuplicateProduct(row.original),
              },
              {
                key: "edit",
                label: t("Edit"),
                icon: Pencil,
                onClick: () => handleUpdate(row.original._id),
              },
              { separator: true },
              {
                key: "delete",
                label: t("Delete"),
                icon: Trash2,
                variant: "delete",
                onClick: () =>
                  handleModalOpen(
                    row.original._id,
                    showingTranslateValue(row.original?.title),
                  ),
              },
            ]}
          />
        ),
        enableSorting: false,
        enableHiding: false,
      },
    ],
    [
      t,
      currency,
      showingTranslateValue,
      handleUpdate,
      handleModalOpen,
      handleDuplicateProduct,
    ],
  );

  return (
    <>
      <div className="flex items-center justify-between py-4 lg:py-8">
        <SectionTitle
          title={t("ProductsPage")}
          description={t("ProductsPageDesc")}
        />
        <ButtonGroup>
          <UploadMany
            title="Products"
            filename={filename}
            isDisabled={isDisabled}
            totalDoc={data?.totalDoc}
            handleSelectFile={handleSelectFile}
            handleUploadMultiple={handleUploadMultiple}
            handleRemoveSelectFile={handleRemoveSelectFile}
          />
          <Button
            variant="bulkAction"
            disabled={selectedIds.length < 1}
            onClick={() => handleUpdateMany(selectedIds)}
            className="space-x-1"
          >
            <FiEdit size={18} />
            <span>{t("BulkAction")}</span>
          </Button>
          <Button
            variant="delete"
            disabled={selectedIds?.length < 1}
            onClick={() =>
              handleDeleteMany(selectedIds, t("Selected") + " " + t("Products"))
            }
            className="space-x-1"
          >
            <FiTrash2 size={18} />
            <span>{t("Delete")}</span>
          </Button>
          <Button variant="create" onClick={toggleDrawer} className="space-x-1">
            <FiPlus size={18} />
            <span>{t("AddProduct")}</span>
          </Button>
        </ButtonGroup>
      </div>

      <DeleteModal
        open={open}
        title={title}
        ids={selectedIds?.length > 0 ? selectedIds : null}
        onOpenChange={() => setOpen(false)}
      />
      <BulkActionDrawer ids={selectedIds} title="Products" />

      <MainDrawer>
        <ProductDrawer id={selectedId} />
      </MainDrawer>

      <AnimatedContent>
        <DynamicTable
          data={data?.products || []}
          columns={columns}
          loading={loading}
          serverSide
          searchText={searchText}
          onSearchChange={(v) => {
            setSearchText(v);
            setCurrentPage(1);
          }}
          searchPlaceholder={t("SearchProduct")}
          filters={[
            {
              title: t("Category"),
              options: categoryOptions,
              value: categoryFilter,
              onChange: (v) => {
                setCategoryFilter(v);
                setCurrentPage(1);
              },
            },
            {
              title: t("Price"),
              options: [
                { label: t("LowtoHigh"), value: "low" },
                { label: t("HightoLow"), value: "high" },
                { label: t("Published"), value: "published" },
                { label: t("Unpublished"), value: "unPublished" },
                { label: t("StatusSelling"), value: "status-selling" },
                { label: t("StatusStock"), value: "status-out-of-stock" },
                { label: t("DateAddedAsc"), value: "date-added-asc" },
                { label: t("DateAddedDesc"), value: "date-added-desc" },
                { label: t("DateUpdatedAsc"), value: "date-updated-asc" },
              ],
              value: sortedField,
              onChange: (v) => {
                setSortedField(v);
                setCurrentPage(1);
              },
            },
          ]}
          onReset={handleResetFilters}
          sorting={sorting}
          setSorting={setSorting}
          rowSelection={rowSelection}
          setRowSelection={setRowSelection}
          setSelectedIds={setSelectedIds}
          columnFilters={columnFilters}
          setColumnFilters={setColumnFilters}
          columnVisibility={columnVisibility}
          setColumnVisibility={setColumnVisibility}
          totalCount={data?.totalDoc || 0}
          totalPages={Math.ceil((data?.totalDoc || 0) / pageSize)}
          currentPage={currentPage}
          pageSize={pageSize}
          onPageChange={setCurrentPage}
          onPageSizeChange={(size) => {
            setPageSize(size);
            setCurrentPage(1);
          }}
        />
      </AnimatedContent>
    </>
  );
};

export default Products;
